### ISSUE TITLE
The ToStorageEvent method fails if the event data assembly is different

### ISSUE THREAD

**Issue by ElasticCoder** [ASOS/SimpleEventStore#14]
The ToStorageEvent method contains the line of code

`object body = Body.ToObject(Type.GetType(BodyType));`

And this takes a fully qualified type name from the metadata. If the writer uses an event defined in an assembly v1 but the reader uses an event defined in assembly v2 the code fails. This means the writer and reader must be kept in line at all times.

We propose that either version numbers are ignored, or better still, an assembly resolver function can be specified to determine how to load the assemblies that contain the event types.

**Comment by asosMikeGore** [comment]
I think this ties into issue #13 somewhat.  Maybe it makes more sense to make the bodyType & metadataType more tied into event names (e.g. OrderPlaced) rather than an assembly qualified name and then make the serialization/deserialization strategy more flexible.

**Comment by asosMikeGore** [comment]
You can now configure how the type names for bodyType and metadataType are created.  This means your events can look like this.  At the moment this is on the configEnhancements branch, let me know if you are happy with this and I'll merge into master.

```json
{
    "id": "d23edcea-f520-483c-bd33-67fa27c41bb1:1",
    "eventId": "35287930-7462-44eb-8d25-daf6771e2291",
    "body": {
        "OrderId": "d23edcea-f520-483c-bd33-67fa27c41bb1"
    },
    "bodyType": "OrderCreated",
    "metadata": null,
    "metadataType": null,
    "streamId": "d23edcea-f520-483c-bd33-67fa27c41bb1",
    "eventNumber": 1,
    "_rid": "42dEAMN8ngABAAAAAAAAAA==",
    "_self": "dbs/42dEAA==/colls/42dEAMN8ngA=/docs/42dEAMN8ngABAAAAAAAAAA==/",
    "_etag": "\"00006e00-0000-0000-0000-595fe9dc0000\"",
    "_attachments": "attachments/",
    "_ts": 1499458012
}
```

**Comment by asosMikeGore** [comment]
Closed as this covers off the original request
