### ISSUE TITLE
How do we want to handle subscriptions moving forward?

### ISSUE THREAD

**Issue by asosMikeGore** [ASOS/SimpleEventStore#15]
At present the current implementation is very basic and isn't production ready.  In order to get it there I'm after some feedback on a few different ideas:
- Use the [DocumentDB change feed processor](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/ChangeFeedProcessor) library.
- Finish off the current implementation.
- Adapt the change feed processor to address it's limitations.

The benefit of using the change feed processor is that it can run across multiple threads, we've proven it's aware of partition splits etc.  However, it forces checkpoints to be taken in Cosmos DB - this means that if you had a subscription to populate an Azure SQL read model then the updating logic would have to be idempotent, rather than writing the updates & snapshot in the same transaction.

The existing implementation addresses this, but may need a fair bit of work to get into a production ready state, plus it may still end up having the limitation of running as a singleton (not sure if this is actually a big deal though in our current domains and throughput requirements without further testing, but won't be as efficient as it could be).

**Comment by asosMikeGore** [comment]
FYI... looks like MS have now released the change feed processor on [nuget.org](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.ChangeFeedProcessor/).  Unfortunately though this looks like it's only targeting .NET Framework 4.5.  Just raised an [issue](https://github.com/Azure/azure-documentdb-dotnet/issues/302) on their repo to see when they'll support it.

**Comment by DaveAurionix** [comment]
For the use cases that I'm considering, the only limitation of CFP that impacts us (that we're aware of) is the current lack of .NET Core support.

We want to avoid coupling event handlers to binary dependencies associated with the inner technology choices of the event publishers.  We don't want event _handlers_ that are coupled to CosmosDB's assemblies used by the event _publisher_.  That rules out having a background poller making HTTP calls to the publisher's CosmosDB API from the event handler's side.  Instead, on the event publisher's side we're making those polling calls and dispatching a batch of messages for each event.  Yes, the event subscribers are coupled to the common messaging technology, but not to the data store technology of the publisher.

In the example given in the opening question, the transaction boundary is around the desired SQL operation and the checkpoint.  For us, it's around the desired SQL operation and the received message.

As such, the fact that CFP forces CosmosDB as the checkpoint store is unfortunate, but not show-stopping.

A bridge or relay between groups of micro-services would isolate the technology coupling to just exist within that group, but for the size that we are at the moment, that would be over-engineering.  If we were a few years down the line, that story might be different.

I suspect that between us we have two differing sets of use cases with two differing ideal solutions!  We might end up using SES to store and retrieve event streams, but ignore SES's Subscription concept and use CFP alongside SES for that instead.  Depends on how this discussion evolves.

**Comment by asosMikeGore** [comment]
@DaveAurionix Just to make sure I've understood correctly, you'd have a catch up subscription that publishes to a message bus, which other services use for integration?  That seems sensible to me and in that particular scenario lack of idempotent writes to the destination isn't a problem as long as the number of duplicate messages published to the bus is low.  You are also expecting out of order messaging in this scenario.

The SQL scenario is more about populating read models specifically.  If we are updating a read model & storing the checkpoint in the same transaction & getting an in-order guarantee (within a stream), this does make read model logic significantly simpler to write.  There's nothing but complexity to be gained from adding a messaging bus in this scenario.

**Comment by DaveAurionix** [comment]
> you'd have a catch up subscription that publishes to a message bus, which other services use for integration

Yes, at the moment.  I must admit that I'm not keen on the idea that CFP would rule out the scenario you describe (or at least make it more complicated) in the future.

**Comment by asosMikeGore** [comment]
The Cosmos DB team have come back and said there is no ETA on the ChangeFeedProcessor NuGet.  I'm going to see if it's possible to take their code and just make it compile - can't see what would stop it given it's just using the Cosmos DB client library from what I've seen so far.

**Comment by asosMikeGore** [comment]
Based on discussions so far both here and internally, it seems there is really no compelling use cases to keep supporting subscriptions.  All our scenarios are handled by the ChangeFeedProcessor, especially now it is on nuget.org.  Therefore, we'll look to remove support.  We can always consider adding in an enhanced version if it is required in the future.

**Comment by asosMikeGore** [comment]
Support has been removed.  This has been applied since we started publishing to nuget.org.  The current recommendation is to use the ChangeFeedProcessor library provided by Microsoft.
