### ISSUE TITLE
Same public methods are available on IStorageEngine as EventStore

### ISSUE THREAD

**Issue by asos-andrewpotts** [ASOS/SimpleEventStore#17]
I incorrectly tried to call the ReadStreamForwards and AppendToStream methods on the IStorageEngine interface from AzureDocumentDbStorageEngineBuilder::Build() rather than on the EventStore.

After checking the documentation again, I realised my mistake. But should those same operations be named the same and be public methods? It allows a new user to make the same mistake.

**Comment by asosMikeGore** [comment]
What I'm wondering moving forward is whether the storage engine should have a lower level interface?  At the moment it's pretty similar to the EventStore interface so I can see why this is confusing.

The benefit of having a lower level interface is that it may open up some extra options e.g. compression, encryption.  We'd need to spike out a few options around this to see if it makes sense to tie these concerns together.

Another way of handling this particular problem could be to see if we can make the fluent configuration API start at the EventStore level - so something like this:

```

return await new EventStoreBuilder()
   .UseAzureDocumentDb(storageEngineBuilder => {
      // Standard AzureDocumentDbStorageEngine concerns then are setup here e.g. UseCollection
})
.Build()
.Initalise();
```

Let me know what you think.

**Comment by asosMikeGore** [comment]
Closing this off as there has been no further follow up.
