### ISSUE TITLE
SubscriptionOptions required on constructor - should it be on SubscribeToAll?

### ISSUE THREAD

**Issue by ElasticCoder** [ASOS/SimpleEventStore#3]
I am creating an Event Store for which I do not want to create a catch-up subscription. Yet I am obliged to provide SubscriptionOptions to the constructor. 

Should this be moved to the SubscribeToAll method?

**Comment by stevewgh** [comment]
I'm working on something that should make this less of an issue.

I'm adding support for snapshots and it ended up being yet another parameter on the ctor for the storage engine, so I've taken a different approach using a builder + extension method pattern. This is very similar to the app builder pattern in ASP.Net Core. Using this pattern the SubscriptionOptions would be a passed to a Subscription method on the builder, required only if you are setting up subscriptions.

I've not pushed it to my repo yet, but once I have I'll issue a PR so I can get feedback on it.

**Comment by asosMikeGore** [comment]
I don't think we should provide snapshot support on the event store.  They are different concerns.  I know NEventStore allows this, but you should be able to use a different storage engine for snapshots vs. the event store if you wanted to.  Plus, if you wanted to you can just model snapshots as streams.

I do like the idea of simplifying the constructor configuration though.

**Comment by stevewgh** [comment]
This implementation of snapshots wouldn't change the current storage engine, which remains totally ignorant of snapshots. The event store and snapshot system remain separate concerns but from a consumer point of view they are easy to use together.

```
var builder = new StorageEngineBuilder();
builder.UseDocumentDb(client).WithSnapshots(options)
```

To keep things separate this feature could be placed into its own repo / nuget package?

**Comment by asosMikeGore** [comment]
@ElasticCoder Worth noting that if you don't need the subscription feature, you can pass in null for the options in the current version.

**Comment by asosMikeGore** [comment]
@ElasticCoder @stevewgh @PeterStephenson I've just pushed a branch that provides a builder for the storage engine.  Let me know what you think.  Here's an example of how to use it:
```csharp
DocumentClient client = new DocumentClient(new Uri(documentDbUri), authKey);

return await new AzureDocumentDbStorageEngineBuilder(client, databaseName)
   .UseCollection(o =>
   {
      o.ConsistencyLevel = consistencyLevelEnum;
      o.CollectionRequestUnits = 400;
   })
   .UseSubscriptions(o =>
   {
      o.MaxItemCount = 1;
      o.PollEvery = TimeSpan.FromSeconds(0.5);
   })
   .Build()
   .Initialise();
```
Note that this is a breaking change as I've made the storage engine internal to force the use of the builder. If you prefer this, I'll merge it in.

**Comment by asosMikeGore** [comment]
Pushed API change above to master
