### ISSUE TITLE
Possible resource leak: need to call Dispose on CosmosDB queries (fix referenced)

### ISSUE THREAD

**Issue by DaveAurionix** [ASOS/SimpleEventStore#38]
Recent performance tests led us to a code review.  During that review we noticed that CosmosDB query objects were not being Disposed.

There's a fix here: https://github.com/GivePenny/SimpleEventStore/commit/414893d55d8bf49800971ceba70052b4f4e79fc9

Would a PR into ASOS' master be appreciated?

**Comment by asos-andrewpotts** [comment]
Thank you @DaveAurionix for highlighting this.
I can see now that the code has moved on and is using the new SDK, and also incorporates the using block. Therefore I will close this issue as 'already fixed'.
