### ISSUE TITLE
Exceptions in Subscription polling loop are silently swallowed

### ISSUE THREAD

**Issue by DaveAurionix** [ASOS/SimpleEventStore#4]
The Start method of the Subscription class uses Task.Run but there is no "await" on the resulting Task instance.  This means that any exception thrown whilst polling DocumentDB will be silently caught and stored against the Task by the .NET Framework, but then never re-thrown for the consumer to react to.  Exceptions are typically thrown by the Framework when the Task is awaited.

This can manifest itself as an issue if, for example, the network connection to DocumentDB becomes unavailable.  The polling loop will stop leaving the Task in a Faulted state but the consuming application is unaware that the subscription has stalled.

Apologies for filing an issue rather than a fix-PR, I think the possible solutions would need discussion first.

**Comment by DaveAurionix** [comment]
P.S. Because the exception is effectively silently swallowed, this means that any solution that monitors the process health (e.g. Service Fabric) to maintain one healthy "singleton" instance will not notice that the subscription has stopped polling.  The process won't be killed and a new instance won't be spun up.

**Comment by asosMikeGore** [comment]
@DaveAurionix @ElasticCoder @PeterStephenson thought it was worth discussing how we want to handle subscriptions moving forward. I have opened up issue #15 so we can further discuss prior to investing to much additional effort into fixing bugs with the current approach.

**Comment by asosMikeGore** [comment]
Just committed an initial set of enhancements around this on the "subscriptionEnhancements" branch.  The API changes are based on how Event Store [handles catch up subscriptions](https://geteventstore.com/blog/20130306/getting-started-part-3-subscriptions/) - I did spike out a few alternatives, but they all ended up more complex.

**Comment by asosMikeGore** [comment]
All outstanding tests that needed to be written are now completed and passing, so closing this issue.
