### ISSUE TITLE
Rename AzureDocumentDb to CosmosDb

### ISSUE THREAD

**Issue by ElasticCoder** [ASOS/SimpleEventStore#6]
Following the product rename, can we update the code to refer to CosmosDb?

**Comment by asosMikeGore** [comment]
I would prefer if the package was aligned to the client library that MS provide.  At present both of their client libraries are still referring to DocumentDB.  This makes sense as this library is for their DocumentDB (SQL) library.  I don't think it provides table & graph APIs.

**Comment by asosMikeGore** [comment]
Closing as there has been no further follow up.
