### ISSUE TITLE
Synk Vulnerability in SimpleEventStore.CosmosDb

### ISSUE THREAD

**Issue by asos-idreesrabani** [ASOS/SimpleEventStore#72]
**Issue**
Snyk has identified a vulnerability in the following package:
Asos.SimpleEventStore.CosmosDb@5.0.11 › Microsoft.Azure.Cosmos@3.10.1 › System.ServiceModel.Primitives@4.5.0

**Solution**
To fix this, update the Microsoft.Azure.Cosmos package to the latest version [(v3.32.0)](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.32.0#versions-body-tab), which no longer uses the [System.ServiceModel.Primitives thus reducing our vulnerability to attacks](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.32.0#dependencies-body-tab).

#71 Includes the change required to mitigate this risk.

**Comment by asos-andrewpotts** [comment]
Merged.
