### ISSUE TITLE
Retry logic on catch-up subscription

### ISSUE THREAD

**Issue by ElasticCoder** [ASOS/SimpleEventStore#9]
Doing testing we found that sometimes the change feed announces changes before you can actually retrieve the document (e.g. it has not fully commited across the replicas). This typically occurs when the susbcription has 'caught up' and there is not much load on the system.

The Microsoft implementation handles this; it throws an internal exception, waits a little time and then retries. It results in a barely noticeable delay, but you get your document.

We believe the catchup subscription is silently swallowing these exceptions and it results in a missing document. 

I will ask the team to test this further, but I have logged the issue for now in case someone else spots similar behaviour first.

**Comment by DaveAurionix** [comment]
Yeah - this is affected / made less obvious by the wider issue https://github.com/ASOS/SimpleEventStore/issues/4

**Comment by asosMikeGore** [comment]
Closing this issue so we can merge into the discussion for issue #4
